/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package d_main;

import a_config.config;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import b_admin.admin_dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import  c_user.user_dashboard;
import b_admin.admin_dashboard;
import a_config.session;
/**
 *
 * @author Administrator
 */
public class login extends javax.swing.JFrame {

    private Object user;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    config.stylePanelButton(LOGIN,    "login");
    config.stylePanelButton(REGISTER, "register");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        REGISTER = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(0, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Username:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        UserField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        UserField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        UserField.setPreferredSize(new java.awt.Dimension(350, 40));
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        bg.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Password:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        PasswordField.setPreferredSize(new java.awt.Dimension(350, 40));
        bg.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login to Your Account");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 390, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Don't have an account?");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (1).png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 80));

        LOGIN.setBackground(new java.awt.Color(26, 26, 46));
        LOGIN.setForeground(new java.awt.Color(0, 153, 153));
        LOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGINMouseExited(evt);
            }
        });
        LOGIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");
        login.setMaximumSize(new java.awt.Dimension(62, 22));
        login.setMinimumSize(new java.awt.Dimension(62, 22));
        login.setPreferredSize(new java.awt.Dimension(62, 22));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        LOGIN.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        bg.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 30));

        REGISTER.setBackground(new java.awt.Color(26, 26, 46));
        REGISTER.setForeground(new java.awt.Color(0, 153, 153));
        REGISTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTERMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REGISTERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REGISTERMouseExited(evt);
            }
        });
        REGISTER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTER");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        REGISTER.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        bg.add(REGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 110, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked

   String user = UserField.getText();
    String pass = new String(PasswordField.getPassword());
    String hashedLoginPass = config.hashPassword(pass);

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both username and password!");
        return;
    }

    try (Connection conn = config.connectDB()) {
        String query = "SELECT * FROM users WHERE u_username = ? AND u_password = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, user);
        pst.setString(2, hashedLoginPass);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // THE SAFETY NET: Initialize and fill the singleton session immediately
            session sess = session.getInstance();
            sess.setId(rs.getInt("u_id"));
            sess.setUsername(rs.getString("u_username"));
            sess.setFname(rs.getString("u_fname"));
            sess.setLname(rs.getString("u_lname"));
            sess.setAccnum(rs.getString("u_accnum"));
            sess.setEmail(rs.getString("u_email"));
            sess.setRole(rs.getString("u_role"));
            sess.setAddress(rs.getString("u_address"));
            sess.setPath(rs.getString("u_image"));

            String status = rs.getString("u_status");
            String role = sess.getRole();

            // 1. Check Account Status
            if (status.equalsIgnoreCase("Pending") && !role.equalsIgnoreCase("Admin")) {
                JOptionPane.showMessageDialog(null, "Your account is still Pending approval.");
                return;
            }

            JOptionPane.showMessageDialog(null, "Login Successful! Welcome, " + sess.getFname());

            // 2. Redirect based on role
            // We still pass the username as a string, but the Dashboard will 
            // now have the session data as a "Safety Net".
            if (role.equalsIgnoreCase("Admin")) {
                new admin_dashboard(sess.getUsername()).setVisible(true);
            } else {
                new user_dashboard(sess.getUsername()).setVisible(true);
            }
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }

    }//GEN-LAST:event_loginMouseClicked

    private void LOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseClicked
        String user = UserField.getText();
    String pass = new String(PasswordField.getPassword());

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both username and password!");
        return;
    }

    try (Connection conn = config.connectDB()) {
        // Query to check credentials and get user details
        String query = "SELECT * FROM users WHERE u_username = ? AND u_password = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, user);
        pst.setString(2, pass);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String status = rs.getString("u_status");
            String role = rs.getString("u_role");

            // 1. Check if the account is still Pending (unless they are an Admin)
            if (status.equalsIgnoreCase("Pending") && !role.equalsIgnoreCase("Admin")) {
                JOptionPane.showMessageDialog(null, "Your account is still Pending approval.\nPlease contact the administrator.");
                return;
            }

            // 2. If active or Admin, set up the session
            config.usersession sess = config.usersession.getInstance();
            sess.setId(rs.getInt("u_id"));
            sess.setFname(rs.getString("u_username")); // Or u_fname if you have that column
            sess.setRole(role);
            sess.setAccnum(rs.getString("u_accnum"));

            JOptionPane.showMessageDialog(null, "Login Successful! Welcome, " + user);

            // 3. Redirect based on role
            if (role.equalsIgnoreCase("Admin")) {
                new admin_dashboard().setVisible(true);
            } else {
                new user_dashboard().setVisible(true);
            }
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_LOGINMouseClicked

    private void LOGINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINMouseEntered

    private void LOGINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        register reg = new register();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void REGISTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTERMouseClicked
        register reg = new register();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_REGISTERMouseClicked

    private void REGISTERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTERMouseEntered

    }//GEN-LAST:event_REGISTERMouseEntered

    private void REGISTERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTERMouseExited

    }//GEN-LAST:event_REGISTERMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel REGISTER;
    private javax.swing.JTextField UserField;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel login;
    // End of variables declaration//GEN-END:variables
}
