/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package d_main;
import a_config.config;

/**
 *
 * @author juls
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register1
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernamefield1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        LOGIN = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        register2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address_field = new javax.swing.JTextField();
        fname_field = new javax.swing.JTextField();
        lname_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(0, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (1).png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 80));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Account");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 350, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Username:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        usernamefield1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernamefield1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        usernamefield1.setPreferredSize(new java.awt.Dimension(350, 40));
        usernamefield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefield1ActionPerformed(evt);
            }
        });
        bg.add(usernamefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 210, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Email:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        emailfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        emailfield.setPreferredSize(new java.awt.Dimension(350, 40));
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        bg.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 210, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Password:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 30));

        passwordfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passwordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        passwordfield.setPreferredSize(new java.awt.Dimension(350, 40));
        bg.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 210, 30));

        LOGIN.setBackground(new java.awt.Color(26, 26, 46));
        LOGIN.setForeground(new java.awt.Color(0, 153, 153));
        LOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGINMouseExited(evt);
            }
        });
        LOGIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("REGISTER");
        login.setMaximumSize(new java.awt.Dimension(62, 22));
        login.setMinimumSize(new java.awt.Dimension(62, 22));
        login.setPreferredSize(new java.awt.Dimension(62, 22));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        LOGIN.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        bg.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 110, 30));

        register2.setBackground(new java.awt.Color(26, 26, 46));
        register2.setForeground(new java.awt.Color(0, 153, 153));
        register2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register2MouseExited(evt);
            }
        });
        register2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("LOGIN");
        jLabel12.setMaximumSize(new java.awt.Dimension(62, 22));
        jLabel12.setMinimumSize(new java.awt.Dimension(62, 22));
        jLabel12.setPreferredSize(new java.awt.Dimension(62, 22));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        register2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        bg.add(register2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Already have an account?");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("First Name: ");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Last Name:");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Address:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 150, 30));
        bg.add(address_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 210, 30));
        bg.add(fname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 210, 30));
        bg.add(lname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 210, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefield1ActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
    String username = usernamefield1.getText();
    String email = emailfield.getText();
    String pass = new String(passwordfield.getPassword());
    
    // GET THE NEW FIELDS HERE
    String firstName = fname_field.getText(); 
    String lastName = lname_field.getText();
    String address = address_field.getText();
    
    String hashedPass = config.hashPassword(pass);

    // Update validation to check new fields
    if (username.isEmpty() || email.isEmpty() || pass.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || address.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        return;
    }

    config conf = new config(); 
    int nextID = 1;

    try (java.sql.Connection conn = config.connectDB()) {
        // 1. Get the next ID (Same as your code)
        String idQuery = "SELECT MAX(u_id) FROM users";
        try (java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(idQuery)) {
            if (rs.next()) {
                nextID = rs.getInt(1) + 1;
            }
        }

        // 2. Generate Account Number (Same as your code)
        String generatedAccNum = conf.generateAccountNumber();

        // 3. UPDATED INSERT: Added u_fname, u_lname, and u_address
        String userQuery = "INSERT INTO users (u_id, u_username, u_email, u_password, u_role, u_status, u_accnum, u_fname, u_lname, u_address) "
                         + "VALUES (?, ?, ?, ?, 'User', 'Pending', ?, ?, ?, ?)";

        try (java.sql.PreparedStatement pstUser = conn.prepareStatement(userQuery)) {
            pstUser.setInt(1, nextID);
            pstUser.setString(2, username);
            pstUser.setString(3, email);
            pstUser.setString(4, hashedPass);
            pstUser.setString(5, generatedAccNum);
            
            // SET THE NEW VALUES IN THE PREPARED STATEMENT
            pstUser.setString(6, firstName); 
            pstUser.setString(7, lastName);
            pstUser.setString(8, address);
            
            int userInserted = pstUser.executeUpdate();

            if (userInserted > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Registration Successful!\n"
                    + "Your Account Number: " + generatedAccNum + "\n"
                    + "Please wait for admin approval.");

                new login().setVisible(true);
                this.dispose();
            }
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_loginMouseClicked

    private void LOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINMouseClicked

    private void LOGINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINMouseEntered

    private void LOGINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void register2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register2MouseClicked
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_register2MouseClicked

    private void register2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_register2MouseEntered

    private void register2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_register2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LOGIN;
    private javax.swing.JTextField address_field;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname_field;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JPanel register2;
    private javax.swing.JTextField usernamefield1;
    // End of variables declaration//GEN-END:variables
}
