/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_user;

import d_main.login;
import a_config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Administrator
 */
public class BillReceipt extends javax.swing.JFrame {

    public Object Amount;
    public Object Date;
    public Object Status;
    public Object User;

    // KINI NGA CONSTRUCTOR DAPAT MAGTUGMA SA PAG-TAWAG NIMO SA PAYBILL.JAVA
    // Your current BillReceipt constructor:
   // Replace your existing constructor in BillReceipt.java
public BillReceipt(String fullName, String accNum, String billId, String amt, String cash, String method, String date) {
        initComponents();

        // 1. SET THE TEXT DIRECTLY - This prevents the blank screen
        customername.setText(fullName.toUpperCase());
        customeraccountnumber.setText(accNum);
        billid.setText(billId);
        paymentdate.setText(date);
        paymentmethod.setText(method);
        amtpaid.setText("PHP " + amt);
        
        // 2. Fetch the actual Payment ID from the DB so it's not "REC-1"
        loadPaymentId(billId);

    }

// Simplified method to just get the ID
    private void loadPaymentId(String bId) {
        try {            Connection conn = config.connectDB();
            String sql = "SELECT p_id FROM payments WHERE b_id = ? ORDER BY p_id DESC LIMIT 1";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, bId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                paymentid.setText(String.valueOf(rs.getInt("p_id")));
            } else {
                paymentid.setText("PENDING");
            }
            conn.close();
        } catch (Exception e) {
            paymentid.setText("N/A");
        }
    }

    public BillReceipt() {
        initComponents();
    }
    
    private void loadFromDatabase(String billId, String fullName, String accNum, String amt, String method, String date) {
    // 1. Set the data immediately using the parameters passed from PayBill
    // This ensures the receipt is NEVER blank even if the DB query fails.
    customername.setText(fullName.toUpperCase());
    customeraccountnumber.setText(accNum);
    billid.setText(billId);
    paymentdate.setText(date);
    paymentmethod.setText(method);
    amtpaid.setText("PHP " + amt);
    paymentid.setText("LOADING..."); // Temporary placeholder

    try {
        a_config.config conf = new a_config.config();
        java.sql.Connection conn = conf.connectDB();

        // 2. Only fetch the Payment ID from the DB
        String sql = "SELECT p_id FROM payments WHERE b_id = ? ORDER BY p_id DESC LIMIT 1";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        // Use setString instead of parseInt to avoid "NumberFormatException"
        pst.setString(1, billId.trim()); 
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            paymentid.setText(String.valueOf(rs.getInt("p_id")));
        } else {
            paymentid.setText("PENDING");
        }

        rs.close();
        pst.close();
        conn.close();

    } catch (Exception e) {
        paymentid.setText("N/A");
        System.out.println("Receipt DB fetch error: " + e.getMessage());
    }
}

// Mas maayo kung maghimo ka og constructor nga modawat og data para sa resibo
public void displayReceipt(String billID, String amount, String status) {
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customername = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        customeraccountnumber = new javax.swing.JLabel();
        billid = new javax.swing.JLabel();
        paymentid = new javax.swing.JLabel();
        paymentdate = new javax.swing.JLabel();
        paymentmethod = new javax.swing.JLabel();
        amtpaid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Receipt");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jLabel2.setBackground(new java.awt.Color(46, 134, 222));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 134, 222));
        jLabel2.setText("Amount Paid:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 30));

        jLabel3.setText("                _________________________________________________________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, 680, -1));

        jLabel4.setText("                _________________________________________________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 240, 680, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Payment Details");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Customer Info");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        customername.setBackground(new java.awt.Color(46, 134, 222));
        customername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        customername.setText("Name:");
        jPanel1.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, 30));

        jLabel8.setBackground(new java.awt.Color(46, 134, 222));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 134, 222));
        jLabel8.setText("Account Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        jLabel9.setBackground(new java.awt.Color(46, 134, 222));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 134, 222));
        jLabel9.setText("Bill ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 30));

        jLabel10.setBackground(new java.awt.Color(46, 134, 222));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(46, 134, 222));
        jLabel10.setText("Payment ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, 30));

        jLabel11.setBackground(new java.awt.Color(46, 134, 222));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 134, 222));
        jLabel11.setText("Payment Date:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 30));

        jLabel12.setBackground(new java.awt.Color(46, 134, 222));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(46, 134, 222));
        jLabel12.setText("Payment Method");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 30));

        jLabel13.setBackground(new java.awt.Color(46, 134, 222));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(46, 134, 222));
        jLabel13.setText("Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        customeraccountnumber.setBackground(new java.awt.Color(46, 134, 222));
        customeraccountnumber.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customeraccountnumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        customeraccountnumber.setText("AccNumber");
        jPanel1.add(customeraccountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 110, 30));

        billid.setBackground(new java.awt.Color(46, 134, 222));
        billid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        billid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billid.setText("BillID");
        jPanel1.add(billid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 160, 30));

        paymentid.setBackground(new java.awt.Color(46, 134, 222));
        paymentid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        paymentid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentid.setText("PaymentID");
        jPanel1.add(paymentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 160, 30));

        paymentdate.setBackground(new java.awt.Color(46, 134, 222));
        paymentdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        paymentdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentdate.setText("PaymentDate");
        jPanel1.add(paymentdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 160, 30));

        paymentmethod.setBackground(new java.awt.Color(46, 134, 222));
        paymentmethod.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        paymentmethod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentmethod.setText("PaymentMethod");
        jPanel1.add(paymentmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 160, 30));

        amtpaid.setBackground(new java.awt.Color(46, 134, 222));
        amtpaid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        amtpaid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amtpaid.setText("AmountPaid");
        jPanel1.add(amtpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtpaid;
    private javax.swing.JLabel billid;
    private javax.swing.JLabel customeraccountnumber;
    private javax.swing.JLabel customername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paymentdate;
    private javax.swing.JLabel paymentid;
    private javax.swing.JLabel paymentmethod;
    // End of variables declaration//GEN-END:variables

    public void directPrint() {
    try {
        // Kini nga method mokuha sa "jPanel1" (imong receipt design) 
        // ug ipadala derecho sa printer.
        a_config.config conf = new a_config.config();
        conf.printPanel(jPanel1); 
    } catch (Exception e) {
        System.out.println("Print Error: " + e.getMessage());
    }
}
    
  public void loadReceipt(String billId) {
    try {
        a_config.config conf = new a_config.config();
        java.sql.Connection conn = conf.connectDB();
        
        // SQL JOIN: Gi-konektar ang payments (p) ug users (u)
        String sql = "SELECT p.*, u.u_fname, u.u_lname, u.u_accnum FROM payments p " +
                     "JOIN users u ON p.u_accnum = u.u_accnum " +
                     "WHERE p.b_id = ?";
        
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, billId);
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            // I-set ang tanang data nga kulang
            customername.setText(rs.getString("u_fname").toUpperCase() + " " + rs.getString("u_lname").toUpperCase());
            customeraccountnumber.setText(rs.getString("u_accnum"));
            billid.setText(rs.getString("b_id"));
            paymentid.setText("REC-" + rs.getInt("p_id"));
            paymentdate.setText(rs.getString("p_date"));
            paymentmethod.setText(rs.getString("p_method"));
            amtpaid.setText("PHP " + rs.getString("p_amount"));
        } else {
            System.out.println("No payment record found for Bill ID: " + billId);
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error pulling receipt data: " + e.getMessage());
    }
}
}
