/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_user;

import a_config.config;
import static a_config.config.connectDB;
import a_config.config.usersession;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import d_main.login;
import javax.swing.JOptionPane;
import a_config.session;

/**
 *
 * @author Administrator
 */
public class Settings extends javax.swing.JFrame {
    String name; 

    public Settings(String loginName) { // 2. Dawata diri
        initComponents();
        this.name = loginName; // 3. I-save diri
    }

    Settings() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        oldpassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        confirmpass = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HOME = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        BILLS = new javax.swing.JPanel();
        bills = new javax.swing.JLabel();
        PROFILE = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        SETTINGS = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutbtn1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 3, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Password Settings");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 350, 70));

        newpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        newpassword.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel3.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("New Password");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        oldpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        oldpassword.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel3.add(oldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Old Password");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        confirmpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        confirmpass.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel3.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Confirm Password");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        logoutbtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));
        logoutbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 40));

        HOME.setBackground(new java.awt.Color(0, 153, 153));
        HOME.setForeground(new java.awt.Color(0, 153, 153));
        HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOMEMouseExited(evt);
            }
        });
        HOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        HOME.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 170, -1));

        jPanel1.add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 40));

        BILLS.setBackground(new java.awt.Color(0, 153, 153));
        BILLS.setForeground(new java.awt.Color(0, 153, 153));
        BILLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BILLSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BILLSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BILLSMouseExited(evt);
            }
        });
        BILLS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bills.setBackground(new java.awt.Color(0, 153, 153));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("BILLS");
        BILLS.add(bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 160, 20));

        jPanel1.add(BILLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        PROFILE.setBackground(new java.awt.Color(0, 153, 153));
        PROFILE.setForeground(new java.awt.Color(0, 153, 153));
        PROFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROFILEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROFILEMouseExited(evt);
            }
        });
        PROFILE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("PROFILE");
        PROFILE.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        jPanel1.add(PROFILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        SETTINGS.setBackground(new java.awt.Color(0, 204, 204));
        SETTINGS.setForeground(new java.awt.Color(0, 153, 153));
        SETTINGS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETTINGSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETTINGSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETTINGSMouseExited(evt);
            }
        });
        SETTINGS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("SETTINGS");
        SETTINGS.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        jPanel1.add(SETTINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 90));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 500));

        logoutbtn1.setBackground(new java.awt.Color(57, 122, 0));
        logoutbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtn1MouseExited(evt);
            }
        });
        logoutbtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SAVE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        logoutbtn1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, -1));

        jPanel3.add(logoutbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        session.getInstance().logout(this);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked

        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Do you really want to log out?",
            "Logout Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            config conf = new config();
            //conf.logEvent("User Logged Out");
            login loginFrame = new login();
            loginFrame.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Logout cancelled by user.");
        }
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseEntered

    }//GEN-LAST:event_logoutbtnMouseEntered

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseExited

    }//GEN-LAST:event_logoutbtnMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        user_dashboard ud = new user_dashboard(); // I-pasa ang name
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HOMEMouseClicked

    private void HOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseEntered

    }//GEN-LAST:event_HOMEMouseEntered

    private void HOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseExited

    }//GEN-LAST:event_HOMEMouseExited

    private void BILLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseClicked
        UserBills ub = new UserBills(this.name);
        ub.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BILLSMouseClicked

    private void BILLSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseEntered

    }//GEN-LAST:event_BILLSMouseEntered

    private void BILLSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseExited

    }//GEN-LAST:event_BILLSMouseExited

    private void PROFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseClicked
        if (this.name == null || this.name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Session error: Username is missing!");
            return;
        }

        // 2. Tawgon ang Profile class ug i-pasa ang username
        Profile prof = new Profile(this.name);

        // 3. I-pakita ang Profile window
        prof.setVisible(true);

        // 4. I-close (dispose) ang karaan nga Dashboard window
        this.dispose();
    }//GEN-LAST:event_PROFILEMouseClicked

    private void PROFILEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseEntered

    }//GEN-LAST:event_PROFILEMouseEntered

    private void PROFILEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseExited

    }//GEN-LAST:event_PROFILEMouseExited

    private void SETTINGSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseClicked
        Settings set = new Settings(this.name); // I-pasa ang name
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SETTINGSMouseClicked

    private void SETTINGSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseEntered

    }//GEN-LAST:event_SETTINGSMouseEntered

    private void SETTINGSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseExited

    }//GEN-LAST:event_SETTINGSMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            char[] oldPassChars = oldpassword.getPassword();
            char[] newPassChars = newpassword.getPassword();
            char[] confirmPassChars = confirmpass.getPassword();

            String oldPassRaw = new String(oldPassChars).trim();
            String newPassRaw = new String(newPassChars).trim();
            String confirmPassRaw = new String(confirmPassChars).trim();

            if (oldPassRaw.isEmpty() || newPassRaw.isEmpty() || confirmPassRaw.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields are required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (newPassRaw.length() < 8) {
                JOptionPane.showMessageDialog(this, "New password must be at least 8 characters.", "Password Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newPassRaw.equals(confirmPassRaw)) {
                JOptionPane.showMessageDialog(this, "New password and confirmation do not match.", "Mismatch Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Husto nga pagtawag sa hashPassword gikan sa imong config class
            String oldPassHashed = config.hashPassword(oldPassRaw); 
            String newPassHashed = config.hashPassword(newPassRaw);

            usersession session = usersession.getInstance();

            // Pagkuha og connection
            config db = new config();
            Connection conn = db.getConnection(); 
            
            String selectQuery = "SELECT password FROM users WHERE id = ?";
            PreparedStatement selectPst = conn.prepareStatement(selectQuery);
            selectPst.setInt(1, session.getId());
            ResultSet rs = selectPst.executeQuery();

            if (rs.next()) {
                String currentHashedPass = rs.getString("password");

                if (!oldPassHashed.equals(currentHashedPass)) {
                    JOptionPane.showMessageDialog(this, "Old password is incorrect.", "Authentication Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update password in database
            String updateQuery = "UPDATE users SET password = ? WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(updateQuery);
            pst.setString(1, newPassHashed);
            pst.setInt(2, session.getId());

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                session.setPassword(newPassHashed);
                JOptionPane.showMessageDialog(this, "Password changed successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                oldpassword.setText("");
                newpassword.setText("");
                confirmpass.setText("");
            }
            
            conn.close(); // Siguroha nga i-close ang connection

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void logoutbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtn1MouseClicked

    private void logoutbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtn1MouseEntered

    private void logoutbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtn1MouseExited

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BILLS;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel PROFILE;
    private javax.swing.JPanel SETTINGS;
    private javax.swing.JLabel bills;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JPanel logoutbtn1;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JPasswordField oldpassword;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables

    private void logAction(String user_logged_out) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    }
