/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_user;
import a_config.session;
/**
 *
 * @author juls
 */
public class StatementofAccount extends javax.swing.JFrame {

    /**
     * Creates new form StatementofAccount1
     */
    public StatementofAccount() {
        initComponents();
        if (a_config.session.getInstance().getAccnum() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please login first!");
        this.dispose();
    } else {
        displayUserData();
        calculateTotal();
    }
    }
    
    private void displayUserData() {
    a_config.session sess = a_config.session.getInstance();
    customername.setText(sess.getFname() + " " + sess.getLname());
    customeraccountnumber1.setText(sess.getAccnum());
    address.setText(sess.getAddress()); 
}
    private void calculateTotal() {
    try {
        a_config.config conf = new a_config.config();
        java.sql.Connection conn = conf.connectDB();
        
        // Get the current user's ID from the session
        int userID = a_config.session.getInstance().getId();
        
        // SQL to sum up all 'Pending' bills for this user
        String sql = "SELECT SUM(b_amount) AS total FROM bills WHERE u_id = ? AND b_status = 'Pending'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, userID);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            double total = rs.getDouble("total");
            // Update the label with the actual calculated total
            totalamountlabel.setText("PHP " + String.format("%.2f", total));
        }
        
        conn.close();
    } catch (Exception e) {
        System.out.println("Error calculating total: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        customername = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        customeraccountnumber1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalamountlabel = new javax.swing.JLabel();
        address2 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        printreceipt1 = new javax.swing.JButton();
        PRINT = new javax.swing.JPanel();
        print = new javax.swing.JLabel();
        BACK = new javax.swing.JPanel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 250, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(46, 134, 222));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Statement of Account");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 360, 60));

        logo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (2).png"))); // NOI18N
        jPanel3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 120, 80));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jLabel13.setBackground(new java.awt.Color(46, 134, 222));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(46, 134, 222));
        jLabel13.setText("Name:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, 30));

        jLabel8.setBackground(new java.awt.Color(46, 134, 222));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 134, 222));
        jLabel8.setText("Address:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 30));

        jLabel9.setBackground(new java.awt.Color(46, 134, 222));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 134, 222));
        jLabel9.setText("Account Number:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 30));

        customername.setBackground(new java.awt.Color(46, 134, 222));
        customername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customername.setText("Name:");
        jPanel2.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, 30));

        address.setBackground(new java.awt.Color(46, 134, 222));
        address.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        address.setText("address");
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 270, 30));

        customeraccountnumber1.setBackground(new java.awt.Color(46, 134, 222));
        customeraccountnumber1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customeraccountnumber1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customeraccountnumber1.setText("AccNumber");
        jPanel2.add(customeraccountnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 270, 30));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 650, 230));

        totalamountlabel.setBackground(new java.awt.Color(46, 134, 222));
        totalamountlabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        totalamountlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalamountlabel.setText("10,000.00");
        jPanel2.add(totalamountlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 80, 30));

        address2.setBackground(new java.awt.Color(46, 134, 222));
        address2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        address2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        address2.setText("Total Amount Due:");
        jPanel2.add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 140, 30));

        closebtn.setBackground(new java.awt.Color(46, 134, 222));
        closebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closebtn.setText("Close");
        closebtn.setBorder(null);
        closebtn.setPreferredSize(new java.awt.Dimension(350, 40));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel2.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 140, 20));

        printreceipt1.setBackground(new java.awt.Color(46, 134, 222));
        printreceipt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printreceipt1.setText("Print");
        printreceipt1.setBorder(null);
        printreceipt1.setPreferredSize(new java.awt.Dimension(350, 40));
        printreceipt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printreceipt1MouseClicked(evt);
            }
        });
        printreceipt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printreceipt1ActionPerformed(evt);
            }
        });
        jPanel2.add(printreceipt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 140, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        PRINT.setBackground(new java.awt.Color(57, 122, 0));
        PRINT.setForeground(new java.awt.Color(0, 153, 153));
        PRINT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRINTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PRINTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PRINTMouseExited(evt);
            }
        });
        PRINT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setBackground(new java.awt.Color(255, 255, 255));
        print.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("PRINT");
        print.setMaximumSize(new java.awt.Dimension(62, 22));
        print.setMinimumSize(new java.awt.Dimension(62, 22));
        print.setPreferredSize(new java.awt.Dimension(62, 22));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        PRINT.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(PRINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 110, 30));

        BACK.setBackground(new java.awt.Color(26, 26, 46));
        BACK.setForeground(new java.awt.Color(0, 153, 153));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKMouseExited(evt);
            }
        });
        BACK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setMaximumSize(new java.awt.Dimension(62, 22));
        back.setMinimumSize(new java.awt.Dimension(62, 22));
        back.setPreferredSize(new java.awt.Dimension(62, 22));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        BACK.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        user_dashboard uD = new user_dashboard();
        uD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        user_dashboard uD = new user_dashboard();
        uD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void printreceipt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printreceipt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_printreceipt1MouseClicked

    private void printreceipt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printreceipt1ActionPerformed
        java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
        job.setJobName("Print Statement of Account");

        job.setPrintable(new java.awt.print.Printable() {
            @Override
            public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex) {
                if (pageIndex > 0) {
                    return java.awt.print.Printable.NO_SUCH_PAGE;
                }

                java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                g2d.scale(0.8, 0.8);

                // Siguroha nga 'jPanel1' ang variable name sa imong panel sa Design tab
                jPanel1.printAll(graphics);

                return java.awt.print.Printable.PAGE_EXISTS;
            }
        });

        boolean doPrint = job.printDialog();
        if (doPrint) {
            try {
                job.print();
            } catch (java.awt.print.PrinterException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Printer Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_printreceipt1ActionPerformed

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
                java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
        job.setJobName("Print Statement of Account");

        job.setPrintable(new java.awt.print.Printable() {
            @Override
            public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex) {
                if (pageIndex > 0) {
                    return java.awt.print.Printable.NO_SUCH_PAGE;
                }

                java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                g2d.scale(0.8, 0.8);

                // Siguroha nga 'jPanel1' ang variable name sa imong panel sa Design tab
                jPanel1.printAll(graphics);

                return java.awt.print.Printable.PAGE_EXISTS;
            }
        });

        boolean doPrint = job.printDialog();
        if (doPrint) {
            try {
                job.print();
            } catch (java.awt.print.PrinterException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Printer Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_printMouseClicked

    private void PRINTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseClicked
                java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
        job.setJobName("Print Statement of Account");

        job.setPrintable(new java.awt.print.Printable() {
            @Override
            public int print(java.awt.Graphics graphics, java.awt.print.PageFormat pageFormat, int pageIndex) {
                if (pageIndex > 0) {
                    return java.awt.print.Printable.NO_SUCH_PAGE;
                }

                java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                g2d.scale(0.8, 0.8);

                // Siguroha nga 'jPanel1' ang variable name sa imong panel sa Design tab
                jPanel1.printAll(graphics);

                return java.awt.print.Printable.PAGE_EXISTS;
            }
        });

        boolean doPrint = job.printDialog();
        if (doPrint) {
            try {
                job.print();
            } catch (java.awt.print.PrinterException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Printer Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_PRINTMouseClicked

    private void PRINTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTMouseEntered

    private void PRINTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        user_dashboard uD = new user_dashboard();
        uD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        user_dashboard uD = new user_dashboard();
        uD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACKMouseClicked

    private void BACKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKMouseEntered

    private void BACKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatementofAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatementofAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatementofAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatementofAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatementofAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BACK;
    private javax.swing.JPanel PRINT;
    private javax.swing.JLabel address;
    private javax.swing.JLabel address2;
    private javax.swing.JLabel back;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel customeraccountnumber1;
    private javax.swing.JLabel customername;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel print;
    private javax.swing.JButton printreceipt1;
    private javax.swing.JLabel totalamountlabel;
    // End of variables declaration//GEN-END:variables
}
