/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_user;


import a_config.billsmodel;
import a_config.config;
import a_config.config.usersession;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import d_main.login;
import a_config.session;

/**
 *
 * @author juls
 */
    public class UserBills extends javax.swing.JFrame {
        String name;
        private String loginName;
    /**
     * Creates new form UserBills1
     */
    public UserBills(String loginName) {
        this.name = loginName; 
        initComponents();
        displayBills(); 
    }
    public UserBills() {
        initComponents();
        this.name = loginName; 
        displayBills();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mybillstable = new javax.swing.JTable();
        searchfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        welcometxt2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HOME = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        BILLS = new javax.swing.JPanel();
        bills = new javax.swing.JLabel();
        PROFILE = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        SETTINGS = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RECEIPT = new javax.swing.JPanel();
        receipt = new javax.swing.JLabel();
        SOA = new javax.swing.JPanel();
        soa = new javax.swing.JLabel();
        PENDING = new javax.swing.JPanel();
        pending = new javax.swing.JLabel();
        PAID = new javax.swing.JPanel();
        paid = new javax.swing.JLabel();
        PAY = new javax.swing.JPanel();
        pay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mybillstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mybillstable);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 390, 240));

        searchfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        searchfield.setPreferredSize(new java.awt.Dimension(350, 40));
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        jPanel5.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 310, 30));

        searchbtn.setBackground(new java.awt.Color(255, 255, 255));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.setBorder(null);
        searchbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel5.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 70, 30));

        welcometxt2.setBackground(new java.awt.Color(0, 0, 0));
        welcometxt2.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        welcometxt2.setText("My Bills");
        jPanel5.add(welcometxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 150, 50));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        logoutbtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));
        logoutbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 40));

        HOME.setBackground(new java.awt.Color(0, 153, 153));
        HOME.setForeground(new java.awt.Color(0, 153, 153));
        HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOMEMouseExited(evt);
            }
        });
        HOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        HOME.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 170, -1));

        jPanel1.add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 40));

        BILLS.setBackground(new java.awt.Color(0, 204, 204));
        BILLS.setForeground(new java.awt.Color(0, 153, 153));
        BILLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BILLSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BILLSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BILLSMouseExited(evt);
            }
        });
        BILLS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bills.setBackground(new java.awt.Color(0, 153, 153));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("BILLS");
        BILLS.add(bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 160, 20));

        jPanel1.add(BILLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        PROFILE.setBackground(new java.awt.Color(0, 153, 153));
        PROFILE.setForeground(new java.awt.Color(0, 153, 153));
        PROFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROFILEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROFILEMouseExited(evt);
            }
        });
        PROFILE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("PROFILE");
        PROFILE.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        jPanel1.add(PROFILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        SETTINGS.setBackground(new java.awt.Color(0, 153, 153));
        SETTINGS.setForeground(new java.awt.Color(0, 153, 153));
        SETTINGS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETTINGSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETTINGSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETTINGSMouseExited(evt);
            }
        });
        SETTINGS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("SETTINGS");
        SETTINGS.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        jPanel1.add(SETTINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 90));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 500));

        RECEIPT.setBackground(new java.awt.Color(0, 153, 153));
        RECEIPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RECEIPTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RECEIPTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RECEIPTMouseExited(evt);
            }
        });
        RECEIPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt.setBackground(new java.awt.Color(255, 255, 255));
        receipt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        receipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.setText("RECEIPT");
        receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiptMouseClicked(evt);
            }
        });
        RECEIPT.add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 70, 30));

        jPanel5.add(RECEIPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 70, 30));

        SOA.setBackground(new java.awt.Color(0, 153, 153));
        SOA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SOAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SOAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SOAMouseExited(evt);
            }
        });
        SOA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        soa.setBackground(new java.awt.Color(255, 255, 255));
        soa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        soa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soa.setText("SOA");
        soa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soaMouseClicked(evt);
            }
        });
        SOA.add(soa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 70, 30));

        jPanel5.add(SOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 70, 30));

        PENDING.setBackground(new java.awt.Color(0, 153, 153));
        PENDING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDINGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PENDINGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PENDINGMouseExited(evt);
            }
        });
        PENDING.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pending.setBackground(new java.awt.Color(255, 255, 255));
        pending.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pending.setText("BILLS");
        pending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingMouseClicked(evt);
            }
        });
        PENDING.add(pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 70, 30));

        jPanel5.add(PENDING, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 70, 30));

        PAID.setBackground(new java.awt.Color(0, 153, 153));
        PAID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PAIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PAIDMouseExited(evt);
            }
        });
        PAID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paid.setBackground(new java.awt.Color(255, 255, 255));
        paid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        paid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paid.setText("PAID");
        paid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paidMouseClicked(evt);
            }
        });
        PAID.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 70, 30));

        jPanel5.add(PAID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 70, 30));

        PAY.setBackground(new java.awt.Color(0, 153, 153));
        PAY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAYMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PAYMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PAYMouseExited(evt);
            }
        });
        PAY.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay.setText("PAY");
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        PAY.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 70, 30));

        jPanel5.add(PAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 70, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String searchTxt = searchfield.getText().trim();
        DefaultTableModel model = (DefaultTableModel) mybillstable.getModel();

        if (searchTxt.isEmpty()) {
            displayBills(); // Kung walay gi-type, ipakita tanan
        } else {
            model.setRowCount(0);
            try {
                config conf = new config();
                Connection conn = conf.connectDB();

                // Mo-search sa Bill ID o Status para sa maong user lang
                String sql = "SELECT b_id, b_amount, b_due_date, b_status FROM bills "
                + "WHERE u_username = ? AND (b_id LIKE ? OR b_status LIKE ?)";

                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, this.name);
                pst.setString(2, "%" + searchTxt + "%");
                pst.setString(3, "%" + searchTxt + "%");

                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("b_id"),
                        rs.getString("b_amount"),
                        rs.getString("b_due_date"),
                        rs.getString("b_status")
                    });
                }
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Search Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    public void displayBills() {
    DefaultTableModel model = (DefaultTableModel) mybillstable.getModel();
    model.setRowCount(0); 

    try {
        config conf = new config();
        Connection conn = conf.connectDB(); 
        
        int userID = a_config.session.getInstance().getId();
        String sql = "SELECT b_id, b_amount, b_status FROM bills WHERE u_id = ?";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, userID); 
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("b_id"),      
                rs.getString("b_amount"),  
                rs.getString("b_status")    
            });
        }
   
        rs.close();
        pst.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading bills: " + e.getMessage());
    }
}
    
    public void loadBillsByStatus(String status, String loginName) {
    DefaultTableModel model = (DefaultTableModel) mybillstable.getModel();
    model.setRowCount(0); // Clear the table first

    try {
        config conf = new config();
        Connection conn = conf.connectDB(); 
        
        // This query filters by BOTH the user and the status
        String sql = "SELECT b_id, b_amount, b_status FROM bills WHERE b_status = ? AND u_id = (SELECT u_id FROM users WHERE u_username = ?)";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, status);
        pst.setString(2, loginName); 
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("b_id"),         
                rs.getDouble("b_amount"), 
                rs.getString("b_status")   
            });
        }
   
        rs.close();
        pst.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        session.getInstance().logout(this);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked

        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Do you really want to log out?",
            "Logout Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            config conf = new config();
            //conf.logEvent("User Logged Out");
            login loginFrame = new login();
            loginFrame.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Logout cancelled by user.");
        }
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseEntered

    }//GEN-LAST:event_logoutbtnMouseEntered

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseExited

    }//GEN-LAST:event_logoutbtnMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        user_dashboard ud = new user_dashboard(); // I-pasa ang name
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HOMEMouseClicked

    private void HOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseEntered

    }//GEN-LAST:event_HOMEMouseEntered

    private void HOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseExited

    }//GEN-LAST:event_HOMEMouseExited

    private void BILLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseClicked
        UserBills ub = new UserBills(this.name);
        ub.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BILLSMouseClicked

    private void BILLSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseEntered

    }//GEN-LAST:event_BILLSMouseEntered

    private void BILLSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseExited

    }//GEN-LAST:event_BILLSMouseExited

    private void PROFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseClicked
        if (this.name == null || this.name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Session error: Username is missing!");
            return;
        }

        // 2. Tawgon ang Profile class ug i-pasa ang username
        Profile prof = new Profile(this.name);

        // 3. I-pakita ang Profile window
        prof.setVisible(true);

        // 4. I-close (dispose) ang karaan nga Dashboard window
        this.dispose();
    }//GEN-LAST:event_PROFILEMouseClicked

    private void PROFILEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseEntered

    }//GEN-LAST:event_PROFILEMouseEntered

    private void PROFILEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseExited

    }//GEN-LAST:event_PROFILEMouseExited

    private void SETTINGSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseClicked
        Settings set = new Settings(this.name); // I-pasa ang name
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SETTINGSMouseClicked

    private void SETTINGSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseEntered

    }//GEN-LAST:event_SETTINGSMouseEntered

    private void SETTINGSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseExited

    }//GEN-LAST:event_SETTINGSMouseExited

    private void receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseClicked
        int row = mybillstable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a bill first!");
            return;
        }

        // Kuhaon ang data gikan sa selected row
        String id = mybillstable.getValueAt(row, 0).toString();
        String amount = mybillstable.getValueAt(row, 1).toString();
        String status = mybillstable.getValueAt(row, 2).toString();

        // Ablihan ang BillReceipt frame
        BillReceipt receipt = new BillReceipt();
        receipt.setVisible(true);
    }//GEN-LAST:event_receiptMouseClicked

    private void RECEIPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RECEIPTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RECEIPTMouseClicked

    private void RECEIPTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RECEIPTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RECEIPTMouseEntered

    private void RECEIPTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RECEIPTMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RECEIPTMouseExited

    private void soaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soaMouseClicked
        try {
            // Imbis ang karaan nga tawag, siguroha nga husto ang class name
            // Kung StatementOfAccount.java ang file name:
            StatementofAccount soa = new StatementofAccount();
            soa.setVisible(true);
            this.dispose(); // O depende kung gusto nimo isira ang dashboard
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_soaMouseClicked

    private void SOAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SOAMouseClicked

    private void SOAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOAMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SOAMouseEntered

    private void SOAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOAMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SOAMouseExited

    private void pendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingMouseClicked
        loadBillsByStatus("Pending", this.name);
    }//GEN-LAST:event_pendingMouseClicked

    private void PENDINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDINGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PENDINGMouseClicked

    private void PENDINGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDINGMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PENDINGMouseEntered

    private void PENDINGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDINGMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PENDINGMouseExited

    private void paidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidMouseClicked
        loadBillsByStatus("Paid", this.name);
    }//GEN-LAST:event_paidMouseClicked

    private void PAIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PAIDMouseClicked

    private void PAIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAIDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PAIDMouseEntered

    private void PAIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAIDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PAIDMouseExited

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
    int row = mybillstable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Please select a bill to pay.");
    } else {
        // Get data from the table model
        String bid = mybillstable.getValueAt(row, 0).toString();
        String amt = mybillstable.getValueAt(row, 1).toString();
        String status = mybillstable.getValueAt(row, 2).toString();

        if (status.equals("Paid")) {
            JOptionPane.showMessageDialog(null, "This bill is already paid.");
        } else {
            // Pass the Bill ID and Amount to PayBill
            PayBill pb = new PayBill(bid, amt); 
            pb.setVisible(true);
            this.dispose();
        }
    }
    }//GEN-LAST:event_payMouseClicked

    private void PAYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAYMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PAYMouseClicked

    private void PAYMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAYMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PAYMouseEntered

    private void PAYMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAYMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PAYMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BILLS;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel PAID;
    private javax.swing.JPanel PAY;
    private javax.swing.JPanel PENDING;
    private javax.swing.JPanel PROFILE;
    private javax.swing.JPanel RECEIPT;
    private javax.swing.JPanel SETTINGS;
    private javax.swing.JPanel SOA;
    private javax.swing.JLabel bills;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutbtn;
    public javax.swing.JTable mybillstable;
    private javax.swing.JLabel paid;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel pending;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel receipt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel settings;
    private javax.swing.JLabel soa;
    private javax.swing.JLabel welcometxt2;
    // End of variables declaration//GEN-END:variables
}
