/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b_admin;
import a_config.session;
import a_config.config; // Para sa imong database connection
import java.sql.Connection; // Tinuod nga SQL Connection
import java.sql.PreparedStatement; // Tinuod nga SQL PreparedStatement
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import d_main.login;

/**
 *
 * @author Administrator
 */
public class AddBills extends javax.swing.JFrame {

    /**
     * Creates new form AddBills
     */
    String name; // ADD THIS

public AddBills(String loginName) { // ADD THIS CONSTRUCTOR
    initComponents();
    this.name = loginName;
    loadAccountNumbers();

    config.stylePanelButton(PROFILE, "nav");
    config.stylePanelButton(SAVE,      "save");
    config.stylePanelButton(CANCEL,    "cancel");
    config.stylePanelButton(logoutbtn, "logout");
    config.stylePanelButton(HOME,      "nav");
    config.stylePanelButton(BILLS,     "nav-active");
    config.stylePanelButton(PROFILE,   "nav");
    config.stylePanelButton(PROFILE1,  "nav");
    config.stylePanelButton(SETTINGS,  "nav");
}

    
    public AddBills() {
    initComponents();
    loadAccountNumbers();

    config.stylePanelButton(PROFILE, "nav");
    config.stylePanelButton(SAVE,      "save");
    config.stylePanelButton(CANCEL,    "cancel");
    config.stylePanelButton(logoutbtn, "logout");
    config.stylePanelButton(HOME,      "nav");
    config.stylePanelButton(BILLS,     "nav-active");
    config.stylePanelButton(PROFILE,   "nav");
    config.stylePanelButton(SETTINGS,  "nav");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void loadAccountNumbers() {
    try {
        config conf = new config();
        java.sql.Connection conn = conf.connectDB();
        String sql = "SELECT u_accnum FROM users WHERE u_role = 'User'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        accnum_drop.removeAllItems(); // Clear existing items
        accnum_drop.addItem("- Select Account -"); // Add a default prompt

        while (rs.next()) {
            accnum_drop.addItem(rs.getString("u_accnum"));
        }
        
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading accounts: " + e.getMessage());
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        monthcombobox = new javax.swing.JComboBox<>();
        curr_read = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        accnum_drop = new javax.swing.JComboBox<>();
        duedate = new com.toedter.calendar.JDateChooser();
        prev_read = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        SAVE = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        CANCEL = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HOME = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        BILLS = new javax.swing.JPanel();
        bills = new javax.swing.JLabel();
        PROFILE = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        SETTINGS = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PROFILE1 = new javax.swing.JPanel();
        profile2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Bill");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 60));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 570, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Due Date:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Previous kWh:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        monthcombobox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        monthcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "December" }));
        monthcombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        monthcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthcomboboxActionPerformed(evt);
            }
        });
        jPanel5.add(monthcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 200, 40));

        curr_read.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        curr_read.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        curr_read.setPreferredSize(new java.awt.Dimension(350, 40));
        curr_read.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                curr_readKeyTyped(evt);
            }
        });
        jPanel5.add(curr_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 200, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Account Number:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Month:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 110, -1));

        accnum_drop.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        accnum_drop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account Number" }));
        accnum_drop.setPreferredSize(new java.awt.Dimension(350, 40));
        accnum_drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnum_dropActionPerformed(evt);
            }
        });
        jPanel5.add(accnum_drop, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 420, 40));
        jPanel5.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 200, 40));

        prev_read.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        prev_read.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        prev_read.setPreferredSize(new java.awt.Dimension(350, 40));
        prev_read.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prev_readKeyTyped(evt);
            }
        });
        jPanel5.add(prev_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 200, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Current kWh:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 130, -1));

        SAVE.setBackground(new java.awt.Color(57, 122, 0));
        SAVE.setForeground(new java.awt.Color(0, 153, 153));
        SAVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SAVEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SAVEMouseExited(evt);
            }
        });
        SAVE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SAVE");
        jLabel12.setMaximumSize(new java.awt.Dimension(62, 22));
        jLabel12.setMinimumSize(new java.awt.Dimension(62, 22));
        jLabel12.setPreferredSize(new java.awt.Dimension(62, 22));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        SAVE.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel5.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 110, 30));

        CANCEL.setBackground(new java.awt.Color(255, 144, 0));
        CANCEL.setForeground(new java.awt.Color(0, 153, 153));
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANCELMouseExited(evt);
            }
        });
        CANCEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CANCEL");
        jLabel14.setMaximumSize(new java.awt.Dimension(62, 22));
        jLabel14.setMinimumSize(new java.awt.Dimension(62, 22));
        jLabel14.setPreferredSize(new java.awt.Dimension(62, 22));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        CANCEL.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel5.add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 110, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        logoutbtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));
        logoutbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 40));

        HOME.setBackground(new java.awt.Color(0, 153, 153));
        HOME.setForeground(new java.awt.Color(0, 153, 153));
        HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOMEMouseExited(evt);
            }
        });
        HOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("USERS");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        HOME.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 160, -1));

        jPanel1.add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 40));

        BILLS.setBackground(new java.awt.Color(0, 204, 204));
        BILLS.setForeground(new java.awt.Color(0, 153, 153));
        BILLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BILLSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BILLSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BILLSMouseExited(evt);
            }
        });
        BILLS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bills.setBackground(new java.awt.Color(0, 153, 153));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("BILLS");
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
        });
        BILLS.add(bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 150, 20));

        jPanel1.add(BILLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        PROFILE.setBackground(new java.awt.Color(0, 153, 153));
        PROFILE.setForeground(new java.awt.Color(0, 153, 153));
        PROFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROFILEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROFILEMouseExited(evt);
            }
        });
        PROFILE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("PAYMENTS");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        PROFILE.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        jPanel1.add(PROFILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        SETTINGS.setBackground(new java.awt.Color(0, 153, 153));
        SETTINGS.setForeground(new java.awt.Color(0, 153, 153));
        SETTINGS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETTINGSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETTINGSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETTINGSMouseExited(evt);
            }
        });
        SETTINGS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("SETTINGS");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        SETTINGS.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        jPanel1.add(SETTINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 90));

        PROFILE1.setBackground(new java.awt.Color(0, 153, 153));
        PROFILE1.setForeground(new java.awt.Color(0, 153, 153));
        PROFILE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILE1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROFILE1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROFILE1MouseExited(evt);
            }
        });
        PROFILE1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile2.setBackground(new java.awt.Color(255, 255, 255));
        profile2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        profile2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile2.setText("PROFILE");
        profile2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile2MouseClicked(evt);
            }
        });
        PROFILE1.add(profile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        jPanel1.add(PROFILE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 40));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void monthcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthcomboboxActionPerformed

    private void accnum_dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnum_dropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnum_dropActionPerformed

    private void curr_readKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_curr_readKeyTyped
        char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '.') {
                evt.consume(); // This "eats" the keystroke if it's a letter
            }
    }//GEN-LAST:event_curr_readKeyTyped

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
    config conf = new config(); 
    
    // 1. Get values from your UI components
    String accNum = accnum_drop.getSelectedItem().toString();
    String month = monthcombobox.getSelectedItem().toString();
    
    // Assuming you named your new text fields 'prev_read' and 'curr_read'
    String pReadStr = prev_read.getText();
    String cReadStr = curr_read.getText();
    
    // Format the date from JDateChooser properly
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String dateDue = (duedate.getDate() != null) ? sdf.format(duedate.getDate()) : "";

    // 2. Validation: Check if fields are empty or default
    if(accNum.equals("Select Account Number") || month.equals("Select Month") || 
       pReadStr.isEmpty() || cReadStr.isEmpty() || dateDue.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please fill all fields!");
        return;
    }

    try {
        double prev = Double.parseDouble(pReadStr);
        double curr = Double.parseDouble(cReadStr);
        
        // Logical check: Current reading cannot be lower than the previous one
        if (curr < prev) {
            JOptionPane.showMessageDialog(null, "Error: Current reading is lower than previous reading.");
            return;
        }

        // 3. Calculation: (Current - Previous) * Price per kWh
        double kwhUsed = curr - prev;
        double rate = 12.00; // Example rate per kWh
        double totalAmount = kwhUsed * rate; 

        // 4. SQL Insert with the new columns
        String sql = "INSERT INTO bills (u_id, b_month, b_prev_reading, b_curr_reading, b_amount, b_due_date, b_status) "
                   + "VALUES ((SELECT u_id FROM users WHERE u_accnum = ?), ?, ?, ?, ?, ?, 'Pending')";

        try (java.sql.Connection conn = conf.connectDB();
             java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
            
            pst.setString(1, accNum);
            pst.setString(2, month);
            pst.setDouble(3, prev);
            pst.setDouble(4, curr);
            pst.setDouble(5, totalAmount);
            pst.setString(6, dateDue);

            if(pst.executeUpdate() == 1){
                JOptionPane.showMessageDialog(null, "Bill successfully generated!\nTotal Amount: ₱" + totalAmount);
                
                admin_dashboard ad= new admin_dashboard();
                ad.setVisible(true);
                this.dispose();
            }
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numbers for the meter readings.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void SAVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseClicked
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SAVEMouseClicked

    private void SAVEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEMouseEntered

    private void SAVEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEMouseExited

    private void prev_readKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prev_readKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_prev_readKeyTyped

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to cancel? Any unsaved progress will be lost.", 
                "Cancel Confirmation", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            // 2. If the user clicks 'Yes' (YES_OPTION), then proceed to close and return to dashboard
            if (confirm == JOptionPane.YES_OPTION) {
                admin_dashboard ad = new admin_dashboard(); 
                ad.setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void CANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseClicked

    private void CANCELMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseEntered

    private void CANCELMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        session.getInstance().logout(this);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked

        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Do you really want to log out?",
            "Logout Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            config conf = new config();
            //conf.logEvent("User Logged Out");
            login loginFrame = new login();
            loginFrame.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Logout cancelled by user.");
        }
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseEntered

    }//GEN-LAST:event_logoutbtnMouseEntered

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseExited

    }//GEN-LAST:event_logoutbtnMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        admin_dashboard ud = new admin_dashboard(); // I-pasa ang name
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HOMEMouseClicked

    private void HOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseEntered

    }//GEN-LAST:event_HOMEMouseEntered

    private void HOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseExited

    }//GEN-LAST:event_HOMEMouseExited

    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        Bills bp = new Bills(); // Ang page diin makita ang "Add" button
        bp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsMouseClicked

    private void BILLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseClicked

    }//GEN-LAST:event_BILLSMouseClicked

    private void BILLSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseEntered

    }//GEN-LAST:event_BILLSMouseEntered

    private void BILLSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseExited

    }//GEN-LAST:event_BILLSMouseExited

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        Payment1 py = new Payment1();
        py.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void PROFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseClicked

    }//GEN-LAST:event_PROFILEMouseClicked

    private void PROFILEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseEntered

    }//GEN-LAST:event_PROFILEMouseEntered

    private void PROFILEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseExited

    }//GEN-LAST:event_PROFILEMouseExited

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        Setting st = new Setting();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsMouseClicked

    private void SETTINGSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseClicked

    }//GEN-LAST:event_SETTINGSMouseClicked

    private void SETTINGSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseEntered

    }//GEN-LAST:event_SETTINGSMouseEntered

    private void SETTINGSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseExited

    }//GEN-LAST:event_SETTINGSMouseExited

    private void PROFILE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILE1MouseClicked
        
    }//GEN-LAST:event_PROFILE1MouseClicked

    private void PROFILE1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILE1MouseEntered

    }//GEN-LAST:event_PROFILE1MouseEntered

    private void PROFILE1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILE1MouseExited

    }//GEN-LAST:event_PROFILE1MouseExited

    private void profile2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile2MouseClicked
        Profile prf = new Profile();
    prf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_profile2MouseClicked

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BILLS;
    private javax.swing.JPanel CANCEL;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel PROFILE;
    private javax.swing.JPanel PROFILE1;
    private javax.swing.JPanel SAVE;
    public javax.swing.JPanel SETTINGS;
    private javax.swing.JComboBox<String> accnum_drop;
    private javax.swing.JLabel bills;
    private javax.swing.JTextField curr_read;
    private com.toedter.calendar.JDateChooser duedate;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JComboBox<String> monthcombobox;
    private javax.swing.JTextField prev_read;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profile2;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables

}
