/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b_admin;

import a_config.config;
import javax.swing.JOptionPane;
import d_main.login;

/**
 *
 * @author Administrator
 */


public class AddUser extends javax.swing.JFrame {
    
       public String action = "Add"; 
       public String userID;

    public AddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rolecombobox = new javax.swing.JComboBox<>();
        emailfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SAVE = new javax.swing.JPanel();
        adduserbtn = new javax.swing.JLabel();
        CANCEL = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fname_field = new javax.swing.JTextField();
        lname_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        address_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add User");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Role:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, 30));

        rolecombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "User", "Admin", " " }));
        rolecombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        rolecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(rolecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, 30));

        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        emailfield.setPreferredSize(new java.awt.Dimension(350, 40));
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, 30));

        passwordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        passwordfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 30));

        usernamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        usernamefield.setPreferredSize(new java.awt.Dimension(350, 40));
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Username:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 30));

        SAVE.setBackground(new java.awt.Color(57, 122, 0));
        SAVE.setForeground(new java.awt.Color(0, 153, 153));
        SAVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SAVEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SAVEMouseExited(evt);
            }
        });
        SAVE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adduserbtn.setBackground(new java.awt.Color(255, 255, 255));
        adduserbtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        adduserbtn.setForeground(new java.awt.Color(255, 255, 255));
        adduserbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adduserbtn.setText("SAVE");
        adduserbtn.setMaximumSize(new java.awt.Dimension(62, 22));
        adduserbtn.setMinimumSize(new java.awt.Dimension(62, 22));
        adduserbtn.setPreferredSize(new java.awt.Dimension(62, 22));
        adduserbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adduserbtnMouseClicked(evt);
            }
        });
        SAVE.add(adduserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 110, 30));

        CANCEL.setBackground(new java.awt.Color(255, 144, 0));
        CANCEL.setForeground(new java.awt.Color(0, 153, 153));
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANCELMouseExited(evt);
            }
        });
        CANCEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CANCEL");
        jLabel14.setMaximumSize(new java.awt.Dimension(62, 22));
        jLabel14.setMinimumSize(new java.awt.Dimension(62, 22));
        jLabel14.setPreferredSize(new java.awt.Dimension(62, 22));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        CANCEL.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("First Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Last Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, 30));

        fname_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        fname_field.setPreferredSize(new java.awt.Dimension(350, 40));
        fname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(fname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 200, 30));

        lname_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        lname_field.setPreferredSize(new java.awt.Dimension(350, 40));
        lname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lname_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(lname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 200, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 100, 30));

        address_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        address_field.setPreferredSize(new java.awt.Dimension(350, 40));
        address_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(address_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        
    
  
    public void setEditMode(String id, String fname, String lname, String email, String user, String addr, String role) {
    this.action = "Edit";
    this.userID = id; // This will no longer be red
    
    jLabel1.setText("Edit Profile");
    adduserbtn.setText("Update");
    
    fname_field.setText(fname);
    lname_field.setText(lname);
    address_field.setText(addr);
    emailfield.setText(email);
    usernamefield.setText(user);
    rolecombobox.setSelectedItem(role);
    
    passwordfield.setEnabled(false);
    }
    
    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void rolecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolecomboboxActionPerformed

    private void adduserbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserbtnMouseClicked
                String fname = fname_field.getText().trim();
    String lname = lname_field.getText().trim();
    String addr = address_field.getText().trim();
    String email = emailfield.getText().trim();
    String user = usernamefield.getText().trim();
    String pass = new String(passwordfield.getPassword());
    String role = (String) rolecombobox.getSelectedItem();

    // 1. Validation
    if (action.equals("Edit") && role.equals("Admin")) {
        JOptionPane.showMessageDialog(this, "Cannot change user role to Admin! Contact system administrator.");
        return;
    }

    // 1. Validation
    if (fname.isEmpty() || lname.isEmpty() || email.isEmpty() || user.isEmpty() || (action.equals("Add") && pass.isEmpty())) {
        JOptionPane.showMessageDialog(this, "All fields are required!");
        return;
    }

    config conf = new config();

    try (java.sql.Connection con = conf.connectDB()) {
        if (action.equals("Add")) {
            // --- ADD USER LOGIC ---
            String accNum = conf.generateAccountNumber();
            int nextID = 1;
            
            // Logic to find next ID gap (Your existing logic)
            String checkQuery = "SELECT u_id FROM users ORDER BY u_id ASC";
            try (java.sql.Statement st = con.createStatement(); 
                 java.sql.ResultSet rs = st.executeQuery(checkQuery)) {
                if (rs.next()) {
                    if (rs.getInt(1) > 1) { nextID = 1; } 
                    else {
                        String gap = "SELECT u_id + 1 FROM users WHERE (u_id + 1) NOT IN (SELECT u_id FROM users) LIMIT 1";
                        try (java.sql.ResultSet rsG = st.executeQuery(gap)) {
                            if (rsG.next()) nextID = rsG.getInt(1);
                        }
                    }
                }
            }

            String sql = "INSERT INTO users (u_id, u_fname, u_lname, u_email, u_username, u_password, u_role, u_status, u_address, u_accnum, u_image) "
                       + "VALUES (?, ?, ?, ?, ?, ?, ?, 'Active', ?, ?, ?)";
            
            try (java.sql.PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setInt(1, nextID);
                pst.setString(2, fname);
                pst.setString(3, lname);
                pst.setString(4, email);
                pst.setString(5, user);
                pst.setString(6, pass);
                pst.setString(7, role);
                pst.setString(8, addr);
                pst.setString(9, accNum);
                pst.setString(10, "src/user_images/default.png");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "User Added Successfully!");
            }

        } else {
            // --- EDIT/UPDATE USER LOGIC ---
            String sql = "UPDATE users SET u_fname = ?, u_lname = ?, u_email = ?, u_username = ?, u_role = ?, u_address = ? "
                       + "WHERE u_id = ?";
            
            rolecombobox.removeAllItems();
            rolecombobox.addItem("User");
            rolecombobox.setEnabled(false);
            
            try (java.sql.PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setString(1, fname);
                pst.setString(2, lname);
                pst.setString(3, email);
                pst.setString(4, user);
                pst.setString(5, role);
                pst.setString(6, addr);
                pst.setString(7, userID); // The ID we stored in setEditMode
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Profile Updated Successfully!");
            }
        }

        // Return to Dashboard
        new admin_dashboard().setVisible(true);
        this.dispose();

    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_adduserbtnMouseClicked

    private void SAVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseClicked
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SAVEMouseClicked

    private void SAVEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEMouseEntered

    private void SAVEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEMouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to cancel? Any unsaved progress will be lost.", 
                "Cancel Confirmation", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
                                                                                                                                    
                        if (confirm == JOptionPane.YES_OPTION) {                                                    
                admin_dashboard ad = new admin_dashboard(); 
                ad.setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void CANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseClicked

    private void CANCELMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseEntered

    private void CANCELMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELMouseExited

    private void fname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_fieldActionPerformed

    private void lname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_fieldActionPerformed

    private void address_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_fieldActionPerformed

   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CANCEL;
    private javax.swing.JPanel SAVE;
    private javax.swing.JTextField address_field;
    private javax.swing.JLabel adduserbtn;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lname_field;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JComboBox<String> rolecombobox;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables

    private static class secretanswer {

        public secretanswer() {
        }
    }
}
