/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package b_admin;


import c_user.BillReceipt;
import b_admin.Bills;
import b_admin.Logs;
import b_admin.Setting;
import b_admin.admin_dashboard;
import a_config.config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import d_main.login;
import c_user.user_dashboard;
import a_config.session;
import c_user.BillReceipt;
import c_user.user_dashboard;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author juls
 */
public class Payment1 extends javax.swing.JFrame {
String accNum, billID, amount, cash, change, date;
    /**
     * Creates new form Payment1
     */
config db = new config();

public Payment1(String accNum, String billID, String amount, String cash, String change, String date) {
    initComponents(); 
    this.accNum = accNum;
    this.billID = billID;
    this.amount = amount;
    this.cash = cash;
    this.change = change;
    this.date = date;

 
    setupTableColumns(); // Siguraduhin na may columns ang table
    displayData();       // I-load ang mga records galing database
}

    public Payment1() {
        initComponents();
        displayData();

        
        config.stylePanelButton(PROFILE, "nav");
        config.styleButton(addbills,  "add");
        config.styleButton(editbill,  "edit");
        config.styleButton(editbill1, "delete");
        config.styleButton(searchbtn, "search");
        config.stylePanelButton(logoutbtn,  "logout");
        config.stylePanelButton(logoutbtn1, "print");
        config.stylePanelButton(HOME,       "nav");
        config.stylePanelButton(BILLS,      "nav");
        config.stylePanelButton(PROFILE,    "nav-active");
        config.stylePanelButton(SETTINGS,   "nav");
    }
    
private void processPayment(double amount, double cash, double change) {
        config conf = new config();
        String sql = "INSERT INTO payments (p_amount, p_cash, p_change, p_date) "
                   + "VALUES ("+amount+", "+cash+", "+change+", datetime('now'))";
        
        if (conf.insertData(sql) == 1) {
            JOptionPane.showMessageDialog(null, "Payment Successful!\nSukli: " + change);
            
            BillReceipt br = new BillReceipt();
            br.setVisible(true);
            this.dispose();
        }
}


private void setupTableColumns() {
    String[] columnNames = {"Payment ID", "Bill ID", "Amount", "Cash", "Change", "Date"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    paymenttable.setModel(model);
}


  public void displayData() {
    try {
        java.sql.Connection conn = config.connectDB();
        
        // This query connects all 3 tables to get the Account Number
        String sql = "SELECT p.p_id AS 'Payment ID', " +
                     "u.u_accnum AS 'Account #', " + 
                     "p.b_id AS 'Bill ID', " +
                     "p.p_amount AS 'Paid', " +
                     "p.p_date AS 'Date' " +
                     "FROM payments p " +
                     "JOIN bills b ON p.b_id = b.b_id " +
                     "JOIN users u ON b.u_id = u.u_id";

        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        // Fills your JTable
        paymenttable.setModel(DbUtils.resultSetToTableModel(rs));
        
        rs.close();
        pst.close();
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Payment Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HOME = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        BILLS = new javax.swing.JPanel();
        bills = new javax.swing.JLabel();
        PROFILE = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        SETTINGS = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PROFILE1 = new javax.swing.JPanel();
        profile2 = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymenttable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logoutbtn1 = new javax.swing.JPanel();
        print = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addbills = new javax.swing.JButton();
        editbill = new javax.swing.JButton();
        editbill1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        logoutbtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));
        logoutbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 40));

        HOME.setBackground(new java.awt.Color(0, 153, 153));
        HOME.setForeground(new java.awt.Color(0, 153, 153));
        HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HOMEMouseExited(evt);
            }
        });
        HOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("USERS");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        HOME.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 160, -1));

        jPanel1.add(HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 40));

        BILLS.setBackground(new java.awt.Color(0, 153, 153));
        BILLS.setForeground(new java.awt.Color(0, 153, 153));
        BILLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BILLSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BILLSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BILLSMouseExited(evt);
            }
        });
        BILLS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bills.setBackground(new java.awt.Color(0, 153, 153));
        bills.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bills.setText("BILLS");
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
        });
        BILLS.add(bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 150, 20));

        jPanel1.add(BILLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 40));

        PROFILE.setBackground(new java.awt.Color(0, 204, 204));
        PROFILE.setForeground(new java.awt.Color(0, 153, 153));
        PROFILE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROFILEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROFILEMouseExited(evt);
            }
        });
        PROFILE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("PAYMENTS");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        PROFILE.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        jPanel1.add(PROFILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        SETTINGS.setBackground(new java.awt.Color(0, 153, 153));
        SETTINGS.setForeground(new java.awt.Color(0, 153, 153));
        SETTINGS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETTINGSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETTINGSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETTINGSMouseExited(evt);
            }
        });
        SETTINGS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("SETTINGS");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        SETTINGS.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, -1));

        jPanel1.add(SETTINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/powerr (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 90));

        PROFILE1.setBackground(new java.awt.Color(0, 153, 153));
        PROFILE1.setForeground(new java.awt.Color(0, 153, 153));
        PROFILE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROFILE1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROFILE1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PROFILE1MouseExited(evt);
            }
        });
        PROFILE1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile2.setBackground(new java.awt.Color(255, 255, 255));
        profile2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        profile2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile2.setText("PROFILE");
        profile2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile2MouseClicked(evt);
            }
        });
        PROFILE1.add(profile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        jPanel1.add(PROFILE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 500));

        searchfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        searchfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel3.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 170, 30));

        searchbtn.setBackground(new java.awt.Color(44, 62, 80));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.setBorder(null);
        searchbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 70, 30));

        paymenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        paymenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(paymenttable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 460, 250));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Payment History");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 550, 60));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        logoutbtn1.setBackground(new java.awt.Color(26, 26, 46));
        logoutbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtn1MouseExited(evt);
            }
        });
        logoutbtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setBackground(new java.awt.Color(255, 255, 255));
        print.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        print.setForeground(new java.awt.Color(240, 240, 240));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("PRINT");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        logoutbtn1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, -1));
        logoutbtn1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel3.add(logoutbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 110, 40));

        addbills.setBackground(new java.awt.Color(44, 62, 80));
        addbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbills.setText("Add");
        addbills.setBorder(null);
        addbills.setPreferredSize(new java.awt.Dimension(350, 40));
        addbills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillsActionPerformed(evt);
            }
        });
        jPanel3.add(addbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 60, 30));

        editbill.setBackground(new java.awt.Color(44, 62, 80));
        editbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editbill.setText("Edit");
        editbill.setBorder(null);
        editbill.setPreferredSize(new java.awt.Dimension(350, 40));
        editbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbillActionPerformed(evt);
            }
        });
        jPanel3.add(editbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 60, 30));

        editbill1.setBackground(new java.awt.Color(44, 62, 80));
        editbill1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editbill1.setText("Delete");
        editbill1.setBorder(null);
        editbill1.setPreferredSize(new java.awt.Dimension(350, 40));
        editbill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbill1ActionPerformed(evt);
            }
        });
        jPanel3.add(editbill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 60, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        session.getInstance().logout(this);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked

        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Do you really want to log out?",
            "Logout Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            config conf = new config();
            //conf.logEvent("User Logged Out");
            login loginFrame = new login();
            loginFrame.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Logout cancelled by user.");
        }
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseEntered

    }//GEN-LAST:event_logoutbtnMouseEntered

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseExited

    }//GEN-LAST:event_logoutbtnMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        admin_dashboard ud = new admin_dashboard(); // I-pasa ang name
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HOMEMouseClicked

    private void HOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseEntered

    }//GEN-LAST:event_HOMEMouseEntered

    private void HOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HOMEMouseExited

    }//GEN-LAST:event_HOMEMouseExited

    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        Bills bp = new Bills(); // Ang page diin makita ang "Add" button
        bp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsMouseClicked

    private void BILLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseClicked

    }//GEN-LAST:event_BILLSMouseClicked

    private void BILLSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseEntered

    }//GEN-LAST:event_BILLSMouseEntered

    private void BILLSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BILLSMouseExited

    }//GEN-LAST:event_BILLSMouseExited

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        Payment1 py = new Payment1();
    py.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void PROFILEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseClicked

    }//GEN-LAST:event_PROFILEMouseClicked

    private void PROFILEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseEntered

    }//GEN-LAST:event_PROFILEMouseEntered

    private void PROFILEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILEMouseExited

    }//GEN-LAST:event_PROFILEMouseExited

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        Setting st = new Setting();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsMouseClicked

    private void SETTINGSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseClicked

    }//GEN-LAST:event_SETTINGSMouseClicked

    private void SETTINGSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseEntered

    }//GEN-LAST:event_SETTINGSMouseEntered

    private void SETTINGSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGSMouseExited

    }//GEN-LAST:event_SETTINGSMouseExited

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String searchTxt = searchfield.getText().trim();
        try {
            java.sql.Connection conn = config.connectDB();
            // JOIN allows searching for Account Number even though it's in the Users table
            String sql = "SELECT p.p_id AS 'Payment ID', u.u_accnum AS 'Account #', " +
                         "p.p_amount AS 'Paid', p.p_date AS 'Date' " +
                         "FROM payments p " +
                         "JOIN bills b ON p.b_id = b.b_id " +
                         "JOIN users u ON b.u_id = u.u_id " +
                         "WHERE u.u_accnum LIKE ? OR p.p_id LIKE ?";

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + searchTxt + "%");
            pst.setString(2, "%" + searchTxt + "%");
            java.sql.ResultSet rs = pst.executeQuery();

            paymenttable.setModel(DbUtils.resultSetToTableModel(rs));

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Search Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_searchbtnActionPerformed

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
    a_config.session sess = a_config.session.getInstance();
    int currentUID = sess.getId(); 
    
    if (currentUID == 0) {
        JOptionPane.showMessageDialog(null, "Session Error: No User ID found! Please re-login.");
        return;
    }

    // 4. Convert the int to a String when passing it to your printReceipt method
    db.printReceipt(paymenttable, String.valueOf(currentUID));
    }//GEN-LAST:event_printMouseClicked

    private void logoutbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtn1MouseClicked

    private void logoutbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtn1MouseEntered

    private void logoutbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtn1MouseExited

    private void paymenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymenttableMouseClicked
        int row = paymenttable.getSelectedRow();
    String pID = paymenttable.getModel().getValueAt(row, 0).toString();
    String accNum = paymenttable.getModel().getValueAt(row, 1).toString();
    
    // You can use this to open a receipt or a detail view
    JOptionPane.showMessageDialog(null, "Viewing Details for Payment ID: " + pID + "\nAccount: " + accNum);
    }//GEN-LAST:event_paymenttableMouseClicked

    private void addbillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillsActionPerformed
        javax.swing.JTextField fldBillID = new javax.swing.JTextField();
    javax.swing.JTextField fldAccNum = new javax.swing.JTextField();
    javax.swing.JTextField fldAmount = new javax.swing.JTextField();
    javax.swing.JTextField fldCash   = new javax.swing.JTextField();
    javax.swing.JTextField fldMethod = new javax.swing.JTextField();

    Object[] fields = {
        "Bill ID:",    fldBillID,
        "Account #:",  fldAccNum,
        "Amount:",     fldAmount,
        "Cash:",       fldCash,
        "Method:",     fldMethod
    };

    int result = JOptionPane.showConfirmDialog(
        null, fields, "Add Payment", JOptionPane.OK_CANCEL_OPTION
    );

    if (result == JOptionPane.OK_OPTION) {
        try {
            int    bID     = Integer.parseInt(fldBillID.getText().trim());
            double amount  = Double.parseDouble(fldAmount.getText().trim());
            double cash    = Double.parseDouble(fldCash.getText().trim());
            double change  = cash - amount;
            String method  = fldMethod.getText().trim();
            String accNum  = fldAccNum.getText().trim();
            String date    = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

            config conf = new config();
            java.sql.Connection conn = conf.connectDB();
            String sql = "INSERT INTO payments (b_id, p_amount, p_cash, p_change, p_method, p_date, u_accnum) " +
                         "VALUES (?, ?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, bID);
            pst.setDouble(2, amount);
            pst.setDouble(3, cash);
            pst.setDouble(4, change);
            pst.setString(5, method);
            pst.setString(6, date);
            pst.setString(7, accNum);
            int rows = pst.executeUpdate();
            pst.close();
            conn.close();

            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Payment added! Change: " + change);
                displayData();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add payment.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Bill ID, Amount, and Cash.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_addbillsActionPerformed

    private void editbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbillActionPerformed
        int selectedRow = paymenttable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a payment to edit.");
        return;
    }

    int    pID    = Integer.parseInt(paymenttable.getValueAt(selectedRow, 0).toString());
    String accNum = paymenttable.getValueAt(selectedRow, 1).toString();
    String bID    = paymenttable.getValueAt(selectedRow, 2).toString();
    String paid   = paymenttable.getValueAt(selectedRow, 3).toString();
    String date   = paymenttable.getValueAt(selectedRow, 4).toString();

    // Pre-filled input fields
    javax.swing.JTextField fldBillID = new javax.swing.JTextField(bID);
    javax.swing.JTextField fldAccNum = new javax.swing.JTextField(accNum);
    javax.swing.JTextField fldAmount = new javax.swing.JTextField(paid);
    javax.swing.JTextField fldCash   = new javax.swing.JTextField();
    javax.swing.JTextField fldDate   = new javax.swing.JTextField(date);

    Object[] fields = {
        "Bill ID:",   fldBillID,
        "Account #:", fldAccNum,
        "Amount:",    fldAmount,
        "Cash:",      fldCash,
        "Date:",      fldDate
    };

    int result = JOptionPane.showConfirmDialog(
        null, fields, "Edit Payment ID: " + pID, JOptionPane.OK_CANCEL_OPTION
    );

    if (result == JOptionPane.OK_OPTION) {
        try {
            double amount = Double.parseDouble(fldAmount.getText().trim());
            double cash   = Double.parseDouble(fldCash.getText().trim());
            double change = cash - amount;
            String newDate = fldDate.getText().trim();
            String newAcc  = fldAccNum.getText().trim();
            int    newBID  = Integer.parseInt(fldBillID.getText().trim());

            config conf = new config();
            java.sql.Connection conn = conf.connectDB();
            String sql = "UPDATE payments SET b_id = ?, p_amount = ?, p_cash = ?, p_change = ?, p_date = ?, u_accnum = ? " +
                         "WHERE p_id = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, newBID);
            pst.setDouble(2, amount);
            pst.setDouble(3, cash);
            pst.setDouble(4, change);
            pst.setString(5, newDate);
            pst.setString(6, newAcc);
            pst.setInt(7, pID);
            int rows = pst.executeUpdate();
            pst.close();
            conn.close();

            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Payment updated successfully!");
                displayData();
            } else {
                JOptionPane.showMessageDialog(null, "Update failed.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_editbillActionPerformed

    private void editbill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbill1ActionPerformed
        int selectedRow = paymenttable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a payment to delete.");
        return;
    }

    int pID = Integer.parseInt(paymenttable.getValueAt(selectedRow, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(
        null,
        "Are you sure you want to delete Payment ID: " + pID + "?",
        "Delete Confirmation",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            config conf = new config();
            java.sql.Connection conn = conf.connectDB();
            String sql = "DELETE FROM payments WHERE p_id = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, pID);
            int rows = pst.executeUpdate();
            pst.close();
            conn.close();

            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Payment deleted successfully!");
                displayData();
            } else {
                JOptionPane.showMessageDialog(null, "Delete failed. Payment not found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_editbill1ActionPerformed

    private void profile2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile2MouseClicked
        Profile prf = new Profile();
        prf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profile2MouseClicked

    private void PROFILE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILE1MouseClicked

    }//GEN-LAST:event_PROFILE1MouseClicked

    private void PROFILE1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILE1MouseEntered

    }//GEN-LAST:event_PROFILE1MouseEntered

    private void PROFILE1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROFILE1MouseExited

    }//GEN-LAST:event_PROFILE1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BILLS;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel PROFILE;
    private javax.swing.JPanel PROFILE1;
    public javax.swing.JPanel SETTINGS;
    private javax.swing.JButton addbills;
    private javax.swing.JLabel bills;
    private javax.swing.JButton editbill;
    private javax.swing.JButton editbill1;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JPanel logoutbtn1;
    private javax.swing.JTable paymenttable;
    private javax.swing.JLabel print;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profile2;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables
}
